# docker-compose.yml
version: '3'
services:
  flask:
    image: webapp-flask
    build:
      context: ./app/
      dockerfile: Dockerfile-flask
    volumes:
      - "./:/app"
  nginx:
    image: webapp-nginx
    build:
      context: ./server/
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
    depends_on:
      - flask