# Dockerfile-nginx

# FROM nginx:latest
# EXPOSE 80
# EXPOSE 443
# RUN rm /etc/nginx/conf.d/default.conf
# COPY nginx.conf /etc/nginx/conf.d
# COPY nginx.conf /etc/nginx/nginx.conf
# RUN mkdir /etc/nginx/ssl/
# CMD ["nginx", "-g", "daemon off;"]

FROM nginx:1.16
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/
RUN mkdir /etc/nginx/ssl/
CMD ["nginx", "-g", "daemon off;"]